Repository kettle17/group-project-bandcamp, pull requests merged in 2025-06, with the labels that each got.

#30 22 create an architecture diagram
  documentation/architecture_diagram.png
  documentation/user_stories.md
Labels: documentation

#44 Fix example test and add utilities file.
  pipeline/test_extract.py
  pipeline/utilities.py
  requirements.txt
Labels: documentation, enhancement

#45 Add work breakdown diagram
  documentation/work_breakdown_diagram.png
Labels: documentation

#42 Create general READMEs for each subdirectory in project.
  README.md
  pipeline/README.md
  terraform/README.md
Labels: documentation

#55 Add load.py function signatures (TDD).
  pipeline/README.md
  pipeline/load.py
Labels: enhancement

#59 Schema for tracktion database.
  pipeline/schema.sql
Labels: enhancement

#61 Fixed ERD and Schema
  documentation/ERD.png
  pipeline/schema.sql
Labels: bug, documentation, enhancement

#64 Updates to transform function signatures (TDD).
  pipeline/test_transform.py
  pipeline/transform.py
Labels: enhancement, high priority

#67 Implement test functions for load.
  pipeline/load.py
  pipeline/test_load.py
Labels: testing

#72 [PR] Create RDS database using terraform.
  terraform/README.md
  terraform/main.tf
  terraform/variables.tf
Labels: enhancement

#71 [PR] Implement functionality for extract and create additional tests.
  .gitignore
  pipeline/data/.gitignore
  pipeline/extract.py
  pipeline/test_extract.py
  requirements.txt
Labels: documentation, enhancement, high priority, testing

#73 [PR] Create tests for transform.
  .gitignore
  pipeline/README.md
  pipeline/conftest.py
  pipeline/test_load.py
  pipeline/test_transform.py
  pipeline/transform.py
Labels: enhancement, high priority, testing

#85 [PR] Move already defined test fixtures to conftest.py.
  pipeline/conftest.py
  pipeline/test_extract.py
  pipeline/test_load.py
Labels: enhancement, low priority

#81 [PR] Setup basic skeleton for streamlit folder
  streamlit/.gitignore
  streamlit/.streamlit/config.toml
  streamlit/Live_Data.py
  streamlit/README.md
  streamlit/data/.gitignore
  streamlit/pages/Historical_Data.py
  streamlit/visualisations/.gitignore
Labels: documentation, enhancement

#88 [PR] Change column types and add merchandise name column
  pipeline/schema.sql
Labels: bug, refactor

#98 [PR] Fix URL bug in extract.py
  pipeline/extract.py
  pipeline/test_extract.py
Labels: bug, refactor

#106 Fixed schema bug for incremental IDs + removing not null
  pipeline/schema.sql
  streamlit/visualisations/analyse.ipynb
  streamlit/visualisations/data/.gitignore
Labels: bug, enhancement

#104 [PR] Implement functions for load.py
  .github/ISSUE_TEMPLATE/workflows/ci.yml
  README.md
  pipeline/conftest.py
  pipeline/load.py
  pipeline/schema.sql
  pipeline/test_load.py
  requirements.txt
Labels: enhancement

#108 [PR] Create a combination script that combines ETL together FIX
  pipeline/etl_controller.py
  pipeline/load.py
  pipeline/schema.sql
  pipeline/web_scraper.py
Labels: enhancement

#110 Add Dockerfile and ETL lambda handler
  pipeline/Dockerfile
  pipeline/README.md
  pipeline/etl_controller.py
  pipeline/requirements.txt
Labels: enhancement

#129 [PR] Update architecture diagram
  .gitignore
  documentation/architecture_diagram.png
  requirements.txt
Labels: documentation, high priority, refactor

#130 [PR] Create Main page for the dashboard.
  documentation/tracktion_logo.png
  documentation/tracktion_logo_light.png
  documentation/tracktion_logo_transparent_light.png
  streamlit/.gitignore
  streamlit/.streamlit/config.toml
  streamlit/Live_Data.py
  streamlit/pages/Album_Art_Gallery.py
  streamlit/pages/Artists.py
  streamlit/style.css
  streamlit/visualisations/analyse.ipynb
Labels: enhancement, high priority, refactor

#135 [PR] Created simple privacy policy page.
  streamlit/pages/Privacy_Policy.py
Labels: enhancement

#131 [M-TASK] Create a daily pdf report of the previous day's sales.
  README.md
  sales_report/README.md
  sales_report/daily_bandcamp_report_2025-06-18.pdf
  sales_report/daily_bandcamp_report_22025-06-18.pdf
  sales_report/pdf_class.py
  sales_report/queries.py
  sales_report/report.py
  sales_report/requirements.txt
  sales_report/top_artists_by_album.png
  sales_report/top_artists_by_track.png
  sales_report/top_genres_by_album.png
  sales_report/top_genres_by_track.png
  sales_report/tracktion_logo_transparent_light.png
Labels: enhancement

#139 [PR] Bare alerts page
  streamlit/pages/Album_Art_Gallery.py
  streamlit/pages/Alerts.py
  streamlit/pages/Genres.py
  streamlit/pages/Historical_Data.py
  streamlit/pages/Privacy_Policy.py
Labels: documentation, enhancement

#140 [PR] Duplicates stored in database tables tag tables are completely empty.
  pipeline/conftest.py
  pipeline/load.py
  pipeline/schema.sql
  pipeline/test_load.py
  pipeline/test_transform.py
  terraform/etl_lambda/etl_lambda.tf
Labels: bug, high priority, refactor, testing

#147 [PR] Update all of the readme.md files across entire repo.
  alerts/queries.sql
  pipeline/README.md
  streamlit/README.md
  streamlit/data/.gitignore
  terraform/README.md
Labels: documentation, low priority, refactor

#156 [PR] Alert script that gets trending artists
  alerts/Dockerfile
  alerts/alerts.py
  alerts/queries.sql
  alerts/requirements.txt
Labels: enhancement

#165 [PR] Write read me for report directory.
  sales_report/README.md
Labels: documentation

#168 [PR] Extend sales report to use SES
  sales_report/report.py
Labels: enhancement, high priority

#161 [PR] Added new menu to alerts page + added option for users to unsub
  streamlit/pages/Alerts.py
Labels: enhancement

#167 [PR] 1 warning from test + schema fix
  pipeline/load.py
  pipeline/schema.sql
Labels: enhancement

#174 [PR] Read me for alerts directory.
  alerts/README.md
Labels: documentation
